auto-file-renaming=true
bt-load-saved-metadata=true
bt-max-peers=128
bt-save-metadata=true
continue=false
dht-file-path=${HOME}/.cache/aria2/dht.dat
dht-file-path6=${HOME}/.cache/aria2/dht6.dat
dht-listen-port=6881
dir=${HOME}/Downloads
disk-cache=64M
enable-dht=true
enable-peer-exchange=true
enable-rpc=true
file-allocation=falloc
force-save=false
input-file=${HOME}/.local/state/aria2/aria2.session
listen-port=6881
max-concurrent-downloads=5
max-connection-per-server=8
max-overall-upload-limit=100K
min-split-size=10M
rpc-allow-origin-all=true
rpc-listen-all=false
rpc-listen-port=6800
save-session=${HOME}/.local/state/aria2/aria2.session
save-session-interval=60
seed-ratio=0.000000
seed-time=0
split=8
