[idle]
behavior_order = ["lock", "screen-off", "suspend"]
pre_action_fade_seconds = 5.0

[idle.behavior]

[idle.behavior.lock]
enabled = true
timeout = 300
action = "lock"

[idle.behavior.screen-off]
enabled = true
timeout = 600
action = "screen_off"

[idle.behavior.suspend]
enabled = true
timeout = 1800
action = "lock_and_suspend"
