[theme]
mode = "dark"
source = "builtin"
builtin = "Ayu"
community_palette = "Oxocarbon"
wallpaper_scheme = "m3-content"

[theme.templates]
enable_builtin_templates = false
enable_community_templates = false
