Counter=13

[Command_0]
Command=cycle-values video-aspect-override -2 16:9 4:3 21:9
Order=0
OsdMessage=Aspect: ${video-aspect-override}
Type=shortcut

[Command_1]
Command=set cache yes
Order=1
SetOnStartup=true
Type=startup

[Command_10]
Command=set audio-buffer 1
Order=10
SetOnStartup=true
Type=startup

[Command_11]
Command=set video-sync display-resample
Order=11
SetOnStartup=true
Type=startup

[Command_12]
Command=set interpolation yes
Order=12
SetOnStartup=true
Type=startup

[Command_2]
Command=set cache-on-disk no
Order=2
SetOnStartup=true
Type=startup

[Command_3]
Command=set cache-secs 3600000
Order=3
SetOnStartup=true
Type=startup

[Command_4]
Command=set demuxer-max-bytes 16384MiB
Order=4
SetOnStartup=true
Type=startup

[Command_5]
Command=set demuxer-max-back-bytes 4096MiB
Order=5
SetOnStartup=true
Type=startup

[Command_6]
Command=set demuxer-seekable-cache yes
Order=6
SetOnStartup=true
Type=startup

[Command_7]
Command=set demuxer-cache-wait no
Order=7
SetOnStartup=true
Type=startup

[Command_8]
Command=set cache-pause-initial no
Order=8
SetOnStartup=true
Type=startup

[Command_9]
Command=set demuxer-hysteresis-secs 0
Order=9
SetOnStartup=true
Type=startup
