[General]
ColorScheme=Breeze Dark
GuiStyle=Breeze
MaxRecentFiles=0
OsdFontSize=16
ShowPreviewThumbnail=true

[Playback]
RestoreFilePosition=true

[Playlist]
BigFontFullscreen=false
ShowMediaTitle=false
Style=withThumbnails

[Video]
ScreenshotFormat=png
