[Shortcuts]
Command_0=A
playNextAction=]
playPreviousAction=[
playbackSpeedDecreaseAction=
playbackSpeedIncreaseAction=
seekBackwardBigAction=Alt+Left
seekForwardBigAction=Alt+Right
volumeDownAction=Down
volumeUpAction=Up
