shell-integration-features = cursor,sudo,title,ssh-env,ssh-terminfo,path

scrollback-limit = 104857600

notify-on-command-finish = unfocused
notify-on-command-finish-action = notify,no-bell
notify-on-command-finish-after = 10s
